### ISSUE TITLE
Prettier自動フォーマットが機能しない

### ISSUE THREAD

**Issue by kei615ykhm** [kei615ykhm/udemy-notion-next-blog#6]
## 概要
このIssueは、VSCodeでのPrettier自動フォーマットが、特にpagesディレクトリ内のtsxファイルに対して機能していない問題に対してのご意見やご助言をいただきたく作成しました。

## 経緯
78f42f7da4fa06446917e7a858f6617fe5ea9ac4 にてメインページ作成を進めていた際に可読性を維持したいと考え、Prettierの導入を検討しました。

## 作業ブランチ
feature/prettier-app

## 再現手順
1. pagesディレクトリ内のtsxファイルを開く
2. ファイルを編集する
3. 保存時に自動フォーマットが適用されない
4. 手動でフォーマット（Shift + Alt + F）を試みてもエラーが発生する

## 現在の環境
- OS: Windows11 Home 23H2
- Ubuntu: 24.04 LTS
- node: 20.15.0
- npm: 10.8.1
- VSCode version: 1.91.1
- Prettier version: ^3.2.5
- Next.js version: 14.2.5
- TypeScript version: ^5

### .prettierrc
```json
{
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "printWidth": 100,
  "bracketSpacing": true,
  "arrowParens": "avoid",
  "endOfLine": "lf",
  "jsxSingleQuote": true,
  "parser": "typescript",
  "overrides": [
    {
      "files": "pages/**/*.tsx",
      "options": {
        "semi": true,
        "singleQuote": false
      }
    }
  ]
}
```

### VSCode settings.json (関連部分)
```json
{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "files.autoSave": "onFocusChange",
  "typescript.tsdk": "node_modules/typescript/lib",
  "prettier.requireConfig": true,
  "files.associations": {
    "*.ts": "typescript",
    "*.tsx": "typescriptreact"
  }
}
```

### エラーメッセージ
```terminal
["ERROR" - 11:50:58 PM] Unknown keyword or identifier. Did you mean 'import'? (1:1)
> 1 | inport type { NextPage } from 'next';
    | ^
  2 | import Head from 'next/head';
  3 | import Image from 'next/image';
  4 |
SyntaxError: Unknown keyword or identifier. Did you mean 'import'? (1:1)
> 1 | inport type { NextPage } from 'next';
    | ^
  2 | import Head from 'next/head';
  3 | import Image from 'next/image';
  4 |
```

## 試したこと
1. .prettierrcファイルの設定を調整
2. VSCodeの再起動
3. Prettierの設定を確認（"prettier.requireConfig": true）
4. コードのスペルミスを修正（'inport'を'import'に）
5. 依存関係の再インストール

## 期待される動作
pagesディレクトリ内のtsxファイルに対して、設定したPrettierのルールが正しく適用され、保存時に自動フォーマットされること。

## 実際の動作
自動フォーマットが適用されず、手動でフォーマットを試みるとエラーが発生する。

## その他の情報
- package.jsonの依存関係も確認済み
- .prettierrcファイル名も確認済み
- ESLintも導入しているが、こちらは完全手動で扱っている

## 優先度
中

**Comment by niaka3dayo** [comment]
情報不足だと思います。prettierのVSCode拡張機能側で、VSCode自体の出力ログにどのようなエラーが出ているかのほうが大事かもしれません

**Comment by kei615ykhm** [comment]
アドバイスをいただき、ありがとうございます。
ご指摘を受けてエラーを再度確認したところ、以下の点が明らかになりました。

### 新たに判明したこと
- Prettierがフォーマットを適用できなかった原因が他にもあることを見逃していました。実際、[このIssue](https://github.com/kei615ykhm/udemy-notion-next-blog/issues/6#issue-2424704010)でコードのスペルミスを修正しましたが、さらに他のタイプミスも修正したところ、期待通りの動作になりました。
- jsonファイルの設定を見直していた際、不必要なセミコロンの変更が行われていることに気づきました。

### 勘違いしていたこと
- tsxファイルの余白や行間などのフォーマットは正しく動作していました。
- Prettierがスペルミスには完全に対応できないことを理解しておらず、誤解していた結果、正しい動作をしていないと勘違いをしてしまいました。


### jsonファイルに出力されたエラーメッセージ
```terminal
["ERROR" - 11:56:24 PM] Error formatting document.
["ERROR" - 11:56:24 PM] ';' expected. (2:9)
  1 | {
> 2 |   "semi": false,
    |         ^
  3 |   "singleQuote": true,
  4 |   "tabWidth": 2,
  5 |   "trailingComma": "es5",
SyntaxError: ';' expected. (2:9)
  1 | {
> 2 |   "semi": false,
    |         ^
  3 |   "singleQuote": true,
  4 |   "tabWidth": 2,
  5 |   "trailingComma": "es5",
```

これらのことから、いくつかの課題を見つけ、以下のような対応策を行いました。
特に、`.vscode`設定の書き方は大きく見直す必要があると感じています。

## 問題点
1. Prettierの動作原理や、VSCode拡張機能版とnpm版の違いに対する理解不足が全体に関わる根本的な問題点でした。
2. jsonファイルなどに対して不必要なセミコロンやクォーテーションの変更が行われていました。

## 原因の推測
- VSCodeの拡張機能としてのPrettierとnpm版のPrettierが設定ファイルを参照していますが、設定の優先順位や適用範囲が混在しているためです。
- 設定がプロジェクト全体で統一されておらず、意図しないフォーマットが適用されているようです。

## 対応策
VSCode拡張機能版とnpm版の役割の違いと区分に対する知識を学び直した上で、それぞれのファイルに対して明示的なフォーマットの指示を出すように記述します。

1. VSCodeの設定を以下のように変更しました。
### .vscode/settings.json
```json
{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "files.autoSave": "onFocusChange",
  "typescript.tsdk": "node_modules/typescript/lib",
  "prettier.requireConfig": true,
  "files.associations": {
    "*.ts": "typescript",
    "*.tsx": "typescriptreact",
    "*.json": "json"
  }
}
```

2. npm版Prettierの設定を以下のとおりに変更しました。
### .prettierrc
```json
{
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "printWidth": 100,
  "bracketSpacing": true,
  "arrowParens": "avoid",
  "endOfLine": "lf",
  "jsxSingleQuote": true,
  "parser": "typescript",
  "overrides": [
    {
      "files": "*.tsx",
      "options": {
        "semi": true,
        "singleQuote": false
      }
    },
    {
      "files": "*.json",
      "options": {
        "parser": "json",
        "semi": false,
        "singleQuote": false,
        "tabWidth": 2,
        "trailingComma": "none"
      }
    }
  ]
}
```

## 動作チェックの結果
以上の変更を私の環境にて行い、実際に検証しましたところ、私が把握できる範囲では問題点は見られず、このIssueの本題であったtsxファイルへの自動フォーマットについても期待される動作になりました。

ご指導いただいたおかげで、より良い解決策を見つけることができました。引き続きアドバイスをいただければ幸いです。また、今回の対応について追加のご意見やご質問がありましたら、お知らせいただければと思います。

**Comment by kei615ykhm** [comment]
追記いたします。

`main`ブランチに統合するためのチェックを行っている段階で、新たな問題を発見しました。以下は、状況説明と対応策の説明になります。

## 問題点
 - 保存時の自動フォーマットを行った際、`.ts`、`.mjs`ファイルにて`;（セミコロン）`が削除されてしまいました。
- シングルクォーテーションとダブルクォーテーションが混在して、可読性が悪くなっていました。

## 原因の推測
期待する動作にならないファイルに対するセミコロンとクォーテーションの扱いが明確に指示されていないため、`"semi": false`と`"singleQuote": true`のデフォルト設定が適用されているようです。

## 対応策
以下の方針に基づいて、`.prettierrc`ファイルを整理しました。
1. セミコロンを必要とするファイル: `.tsx`、`.ts`、`.mjs`
2. .jsonファイル: セミコロン省略やシングルクォーテーションの適用は不要
3. 全ファイルに対するフォーマット: 余白や行間の調整は自動保存時に適用
4. スタイルガイド: Airbnbの適用例を参考に基準を作成

### .prettierrc
```json
{
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "printWidth": 100,
  "bracketSpacing": true,
  "arrowParens": "avoid",
  "endOfLine": "lf",
  "jsxSingleQuote": true,
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.mjs"],
      "options": {
        "semi": true
      }
    },
    {
      "files": "*.json",
      "options": {
        "parser": "json",
        "semi": false,
        "singleQuote": false,
        "tabWidth": 2,
        "trailingComma": "none"
      }
    }
  ]
}
```

## 動作チェックの結果
以上の変更を私の環境にて行い、実際に検証しましたところ、私が把握できる範囲ではすべて期待通りの結果になりました。
しかし、より詳細なテストは必要だと感じています。

## mainへのマージについて
本Issueにおける主な問題点は解決しましたが、私にとって、この環境構築はまだまだ未知数なものが多く、本番環境のブランチへの統合には不安が残ります。
一方、作業ブランチ: feature/main-pageにてメインページのコーディングを進めていますが、Prettieerのフォーマット無しでの作業は効率が悪く、思うように進んでいないことがプロジェクト全体で抱えている課題になります。

そこで、本番環境のブランチ（`main`）の他に、開発用ブランチ（`div`）を作成し、今後はそちらで作業を行いつつ、調整を続けていくという流れはどうでしょうか？

問題がないようでしたら、Prettierを導入した旨のPRを提出させていただきたいと思います。

## keiコメント
個人学習のプロジェクトなので、ある程度は独断で決定と選択を行いますが、Issueやプルリクは現場開発を想定した書き方を続けていきます。

**Comment by kei615ykhm** [comment]
（上記の提案と提出が可決された体で進めます）

## Issueのcloseと新たな課題への対応について
Prettier自動フォーマットが機能しないという[本題](https://github.com/kei615ykhm/udemy-notion-next-blog/issues/6#issue-2424704010)である問題点は解決したため、このIssueはcloseします。

しかし、新たに開発用ブランチ（`div`）を立ち上げ、実際に開発を進めながらPrettierの設定を調整していくことについては今後も話し合っていくべき項目だと考え、新しく#10 というIssueを作成しました。

### これからの取り組み
今後も開発を進める中で、発見される問題や改善点については速やかに対応し、プロジェクトの安定化と効率化に努めてまいります。皆様からのご意見やご協力をいただきながら、より良い成果を目指して進んでいきたいと思いますので、どうぞよろしくお願いいたします。
